<?php

namespace AppBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends EntityRepository
{
    const REPOSITORY = 'AppBundle:Book';

    /**
     * Get textStatus
     *
     * @return string
     */
    public function getTextStatus($status)
    {
        if($status==0)
        {
            return "Inactivo";
        }
        elseif($status==1)
        {
            return "Activo";
        }
        elseif($status==2)
        {
            return "Borrado";
        }
    }
}