<?php

namespace AppBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends EntityRepository
{
    const REPOSITORY = 'AppBundle:Photo';

    /**
     * Get findOnePhotoByField
     *
     * @return array
     */
    public function findOnePhotoByField($message, $field)
    {
        $result = $this->getEntityManager()
            ->getRepository($this::REPOSITORY)
            ->findOneByUser($field);

        if (!$result)
        {
            return array('message'  => $message . $field);
        }
        else
        {
            return array('result'  => $result);
        }
    }
}
