<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TermRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class TermRepository extends EntityRepository
{
    const REPOSITORY = 'AppBundle:TermData';

    /**
     * Get findAllTerm
     *
     * @return array
     */
    public function findAllTerm($message)
    {
        $result = $this->getEntityManager()
            ->getRepository($this::REPOSITORY)
            ->findAll();

        if (!$result)
        {
            return array('message'  => $message . $result);
        }
        else
        {
            return array('result'  => $result);
        }
    }

    /**
     * Get findOneTermByField
     *
     * @return array
     */
    public function findOneTermByField($message, $field)
    {
        $result = $this->getEntityManager()
            ->getRepository($this::REPOSITORY)
            ->find($field);

        if (!$result)
        {
            return array('message'  => $message . $result);
        }
        else
        {
            return array('result'  => $result);
        }
    }

}
