<?php

namespace AppBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * VocabularyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VocabularyRepository extends EntityRepository
{
    const REPOSITORY = 'AppBundle:Vocabulary';

    // Constant to use it with the field visibility to create a new Vocabulary with visibility in frontend
    const VISIBILITY_VISIBLE =1;

    // Constant to use it with the field status to create a new Vocabulary
    const STATUS_ACTIVATE =1;

    /**
     * Get findAllVocabularies
     *
     * @return array
     */
    public function findAllVocabularies($message)
    {
        $result = $this->getEntityManager()
            ->getRepository($this::REPOSITORY)
            ->findAll();

        if (!$result)
        {
            return array('message'  => $message);
        }
        else
        {
            return array('result'  => $result);
        }
    }

    /**
     * Get findOneVocabularyByField
     *
     * @return array
     */
    public function findOneVocabularyByField($message, $field)
    {
        $result = $this->getEntityManager()
            ->getRepository($this::REPOSITORY)
            ->find($field);

        if (!$result)
        {
            return array('message'  => $message . $field);
        }
        else
        {
            return array('result'  => $result);
        }
    }

    /**
     * Get findVocabulariesVisibles
     *
     * @return array
     */
    public function findVocabulariesVisibles()
    {
        $result = $this->getEntityManager()
            ->getRepository($this::REPOSITORY)
            ->findBy(
                array(
                    'visibility' => $this::VISIBILITY_VISIBLE,
                    'status' => $this::STATUS_ACTIVATE
                ),
                array(
                    'name' => 'ASC'
                )
            );

        return $result;
    }
}
